spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/environment_db
    username: urbanflow
    password: urbanflow

  data:
    redis:
      host: redis
      port: 6379

  kafka:
    bootstrap-servers: kafka:29092

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8081/api/v1/auth/jwks
