apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: urbanflow

resources:
  - namespace.yaml
  - configmap-common.yaml
  - infrastructure/postgres.yaml
  - infrastructure/redis.yaml
  - infrastructure/kafka.yaml
  - apps/core-services.yaml
  - apps/phase2-services.yaml
  - apps/phase3-services.yaml

configMapGenerator:
  - name: postgres-init
    files:
      - 01-create-databases.sql=../../docker/postgres/init/01-create-databases.sql

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: urbanflow
